---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Controller"
      solveButton: false
    - name: module-02
      label: "Ad-Hoc Commands"
      solveButton: false
    - name: module-03
      label: "Playbooks"
      solveButton: false
    - name: module-04
      label: "Projects"
      solveButton: false
    - name: module-05
      label: "Advanced Playbooks"
      solveButton: false
    - name: module-06
      label: "Roles"
      solveButton: false

tabs:
  - name: Controller
    url: https://control-${guid}.${domain}/
  - name: VS Code
    url: https://vscode-${guid}.${domain}
    external: false
  - name: Windows
    url: https://windows-ironrdp-${guid}.${domain}/
    external: false
  - name: Gitea
    url: https://gitea-${guid}.${domain}/
    external: false
  #   modules:
  #     - module-01
  #     - module-02
  #     - module-03
  #   external: false
  # - name: Report Server
  #   url: https://node03-${guid}.${domain}/index.html
  #   external: true
  #   modules:
  #    - module-02
  # - name: Compliance Report
  #   url: https://node02-${guid}.${domain}/oscap-reports/ospp/
  #   external: true
  #   modules:
  #    - module-02
  # - name: Windows UI
  #   url: https://windows-${guid}.${domain}/
  #   external: true
  #   modules:
  #    - module-03
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
